name: Reactibot deployment

on:
  push:
    branches:
      - feature/actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_HASH: ${{ secrets.DISCORD_HASH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          envs: AMPLITUDE_KEY,GITHUB_TOKEN,DISCORD_HASH
          script: |
            cd reactibot
            sudo git checkout feature/actions
            sudo git pull
            sudo docker container stop $(docker container ls -aq)
            sudo docker container rm $(docker container ls -aq)
            sudo docker image prune -f
            sudo docker build -t reactiflux/reactibot:latest .
            sudo docker run -d -e AMPLITUDE_KEY=$AMPLITUDE_KEY -e GITHUB_TOKEN=$GITHUB_TOKEN -e DISCORD_HASH=$DISCORD_HASH reactiflux/reactibot:latest
