name: Deploy

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        git clone https://$GITHUB_TOKEN@github.com/reactiflux/reactibot
        cd reactibot
        git push --quiet $PRODUCTION_GIT_URL
