name: Deploy

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        echo STEP ONE
        git clone https://github.com/reactiflux/reactibot
        echo STEP TWO
        cd reactibot
        echo STEP THREE
        git push --quiet $PRODUCTION_GIT_URL
